# site settings
site-title: Mindful Voices
site-email: hello@mindfulvoices.co
site-description:  Mindfulness Experiments
baseurl: "" # the subpath of your site, e.g. /blog
site-url: "https://bedtime-mv.now.sh" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mindfulvoices
github_username:  

# Build settings
markdown: kramdown


theme: 
plugins:
  - jekyll-feed

# Podcast settings

title:          Mindful Voices
email:          hello@mindfulvoices.co
description:    "Mindfulness meditations for seekers and skeptics alike."
subtitle:       ""
url:            "https://bedtime-mv.now.sh"
lang:           "en"
author:         "Mindful Voices"
copyright:      "&#x2117; &amp; &#xA9; 2020"








# Exclude from processing.

excerpt_separator: "<!--excerpt-->"


# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
